#!/usr/bin/env python

# Dunno why I'm doing this

# In metres
ROVER_RADIUS   = 0.5
HOME_RADIUS    = 5
MARTIAN_RADIUS = 0.4


DELIMITER  = ' '
TERMINATOR = ';'

STATE_BREAK, STATE_ROLL, STATE_ACC = -1, 0, 1
STATE_HARDLEFT, STATE_LEFT, STATE_STRAIGHT, STATE_RIGHT, STATE_HARDRIGHT = -2, -1, 0, 1, 2


MARTIAN, BOULDER, CRATER, HOME = "m", "b", "c", "h"

